version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "patch"
    labels:
      - "dependencies"
    commit-message:
      prefix: "pull-request"
      include: "scope"
    allow:
      - dependency-name: "@discordjs/builders"
      - dependency-name: "discord.js"
      - dependency-name: "discord-player"
      - dependency-name: "discord-api-types"
      - dependency-name: "ytdl-core"
    ignore:
    - dependency-name: "@discordjs/builders"
      update-types: ["version-update:semver-major"]
    - dependency-name: "discord.js"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
    - dependency-name: "discord-player"
      update-types: ["version-update:semver-major"]
    - dependency-name: "discord-api-types"
      update-types: ["version-update:semver-major"]
    - dependency-name: "ytdl-core"
      update-types: ["version-update:semver-major"]
