version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Asia/Jakarta"
    open-pull-requests-limit: 20
    target-branch: "develop"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
    - dependency-name: "discord.js"
      update-types: ["version-update:semver-major"]
    - dependency-name: "@discordjs/builders"
      update-types: ["version-update:semver-major"]
    - dependency-name: "@discordjs/rest"
      update-types: ["version-update:semver-major"]
    - dependency-name: "@discordjs/opus"
      update-types: ["version-update:semver-major"]
    - dependency-name: "@discordjs/voice"
      update-types: ["version-update:semver-major"]
    - dependency-name: "discord-api-types"
      update-types: ["version-update:semver-major"]
    - dependency-name: "discord-giveaways"
      update-types: ["version-update:semver-major"]
    - dependency-name: "discord-player"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
