version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Asia/Jakarta"
    target-branch: "patch"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
    - dependency-name: "novelcovid"
    - dependency-name: "reconlx"
