name: ESLint develop

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  lint:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.14.2]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: install latest npm
      run: npm install npm@latest -g
    - name: install dependencies
      run: npm ci
    - name: run lint
      run: npm test
