name: ESLint

on:
  push:
    branches: [ v5 ]
  pull_request:
    branches: [ v5 ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.10.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      run: npm ci
    - name: run lint
      run: npm test
